include: package:lint/analysis_options_package.yaml

linter:
  rules:
    - combinators_ordering
    - require_trailing_commas
    - unnecessary_library_directive
    - prefer_single_quotes
    - public_member_api_docs